# Generated by Django 6.0.5 on 2026-05-25 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('MISSING_UNIT', 'Missing Unit'), ('INVALID_DATE', 'Invalid Date'), ('DUPLICATE_RECORD', 'Duplicate Record'), ('UNKNOWN_FACILITY', 'Unknown Facility'), ('SUSPICIOUS_QUANTITY', 'Suspicious Quantity'), ('MISSING_REQUIRED_FIELD', 'Missing Required Field'), ('INVALID_AIRPORT_CODE', 'Invalid Airport Code')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('normalized_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='records.normalizedactivityrecord')),
            ],
        ),
    ]
