# Generated by Django 6.0.5 on 2026-05-25 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('raw_payload', models.JSONField()),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('parser_version', models.CharField(default='1.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='imports.importbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('FUEL', 'Fuel'), ('ELECTRICITY', 'Electricity'), ('FLIGHT', 'Flight'), ('HOTEL', 'Hotel'), ('GROUND_TRANSPORT', 'Ground Transport'), ('PROCUREMENT', 'Procurement')], max_length=50)),
                ('scope_category', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=50)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('source_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('facility_name', models.CharField(blank=True, max_length=255, null=True)),
                ('facility_code', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('travel_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('travel_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('estimated_co2e', models.FloatField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked')], default='PENDING', max_length=50)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='tenants.tenant')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_record', to='records.rawrecord')),
            ],
        ),
    ]
